version: "3.9"



services:
  library-api:
    restart: always
    build:
      context: ./server
    image: server
    container_name: server
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - library-mern-api

  client:
    restart: always
    build:
      context: ./client
    image: client
    container_name: client
    volumes:
      - ./app/node_modules
      - ./client:/app
    depends_on:
      - library-api
    networks:
      - library-mern-api

  nginx:
    restart: always
    build:
      context: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - library-api
      - client
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/lib/letsencrypt
    networks:
      - library-mern-api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/lib/letsencrypt
    depends_on:
      - nginx
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - library-mern-api

#volumes:
#  certbot-etc:
#  certbot-var:
#  web-root:
#  dhparam:
#    driver: local
#    driver_opts:
#      type: none
#      device: ./dhparam/
#      o: bind


networks:
  library-mern-api:
    driver: bridge
