version: "3.9"

services:
  library-api:
    restart: always
    build:
      context: ./server
    container_name: test-server-delete
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000
    networks:
      - library-mern-api

  client:
    restart: always
    build:
      context: ./client
    container_name: test-client-delete
    volumes:
      - ./app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
    depends_on:
      - library-api
    networks:
      - library-mern-api

networks:
  library-mern-api:
    driver: bridge
