version: "3.9"



services:
  library-api:
    restart: always
    build:
      context: ./server
    image: server
    container_name: server
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - library-mern-api

  client:
    restart: always
    build:
      context: ./client
    image: client
      container_name: client
    volumes:
      - ./app/node_modules
      - ./client:/app
      - web-root:/usr/share/nginx/html/
    depends_on:
      - library-api
    networks:
      - library-mern-api

  nginx:
    restart: always
    build:
      context: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - library-api
      - client
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
      - web-root:/usr/share/nginx/html/
    networks:
      - library-mern-api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html/
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/ --email 98wonsleved98@gmail.com --agree-tos --no-eff-email --force-renewal -d todoapp.ru  -d www.todoapp.ru

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ./dhparam/
      o: bind


networks:
  library-mern-api:
    driver: bridge
