version: "3.9"



services:
  library-api:
    restart: always
    build:
      context: ./server
#      dockerfile: dev.dev
    container_name: test-server-delete
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - library-mern-api

  client:
    restart: always
    build:
      context: ./client
#      dockerfile: dev.dev
    container_name: test-client-delete
    volumes:
      - ./app/node_modules
      - ./client:/app
    depends_on:
      - library-api
    networks:
      - library-mern-api

  nginx:
    restart: always
    depends_on:
      - library-api
      - client
    build:
      context: ./nginx
#      dockerfile: dev.dev
    ports:
      - 8080:80
    networks:
      - library-mern-api

networks:
  library-mern-api:
    driver: bridge